# Generated by Django 5.2.10 on 2026-01-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='team',
            field=models.CharField(max_length=10),
        ),
    ]
