# Generated by Django 5.2.10 on 2026-01-22 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_participant_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.player'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
