# Generated by Django 5.2.10 on 2026-01-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_room_current_player_room_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='budget',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='participant',
            name='squad_count',
            field=models.IntegerField(default=0),
        ),
    ]
