# Generated by Django 5.2.10 on 2026-01-23 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_participant_budget_participant_squad_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_bid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='highest_bidder',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='last_timer_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='timer',
            field=models.IntegerField(default=15),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='auction.room')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
