# Generated by Django 5.2.10 on 2026-01-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_room_current_bid_room_highest_bidder_room_is_paused_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
