# Generated by Django 5.2.10 on 2026-01-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_alter_participant_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='default_timer_duration',
            field=models.IntegerField(default=15),
        ),
    ]
