# Generated by Django 5.2.10 on 2026-01-27 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_room_default_timer_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='status',
            field=models.CharField(default='SOLD', max_length=20),
        ),
        migrations.AlterField(
            model_name='auction',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.team'),
        ),
    ]
