# Generated by Django 5.2.10 on 2026-01-27 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_auction_status_alter_auction_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='final_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_qualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='playing_xi',
            field=models.ManyToManyField(blank=True, related_name='selected_by', to='auction.player'),
        ),
        migrations.AddField(
            model_name='player',
            name='batting_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='batting_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='economy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='ppi',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='strike_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('LIVE', 'Live Auction'), ('SELECTION', 'Selection Phase'), ('CALCULATING', 'Calculating Winner'), ('COMPLETED', 'Winner Declared')], default='LIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='auction.participant')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to='auction.participant')),
            ],
            options={
                'unique_together': {('voter', 'candidate')},
            },
        ),
    ]
