# Generated by Django 5.2.10 on 2026-01-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_participant_final_score_participant_is_qualified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
