# Generated by Django 5.2.10 on 2026-02-04 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0013_room_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='auction.room')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
